### ISSUE TITLE
introducing state attribute

### ISSUE THREAD

**Issue by ochko** [reallyenglish/ansible-role-virtual-interface#22]
Instead of having `virtual_interfaces` and `virtual_interface_to_remove` we could have `state` attribute so that:

```yaml
virtual_interfaces:
  - name: gre0:
    state: present
    config: |
      !echo Starting \${if}
      description "GRE tunnel"
      up
  - name: gre1:
    state: absent
```

`state` can be omitted, having default value of `present`.
