### ISSUE TITLE
there is no way to remove virtual interface

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-virtual-interface#8]
If you create a virtual interface, but, later, would like to remove it, there is no way to remove the virtual interface.

A possible implementation is something like:

```yaml
virtual_interface:
  gre0:
    action: destroy
```

which destroys the interface.
